package dosAlarms

//import java.lang.Exception;
import com.example.bolnicaServer.model.fact.BlockingFact;

declare SystemEvent
    @role(event)
    @expires(60s)
    ip: String
end

declare SuspiciousIpEvent
    @role(event)
    @expires(60s)
    ip: String
end

rule "Insert system action"
    agenda-group "SystemLog"
	salience 10
    when
        $ip: String()
    then
        SystemEvent event = new SystemEvent();
        System.out.println("Event");
        event.setIp($ip);
        insert(event);
        //delete($u);
end

rule "Alarm Suspicious Ip"
    agenda-group "SystemLog"
    salience 7
    when
        $ip: String()
        $fl:SystemEvent(ip == $ip)
        $num: Number(intValue > 60) from accumulate(
            $fl2: SystemEvent(
                this != $fl,
                ip == $ip,
                this meets[100s] $fl
            ),
            count($fl2)
        )
        not (SuspiciousIpEvent(ip == $ip, this meets[60s] $fl))
    then
        System.out.println("Ulazim ovde alarm");
        System.out.println($num);
        SuspiciousIpEvent alarm = new SuspiciousIpEvent();
        alarm.setIp($ip);
        insert(alarm);
end

rule "Set alarm field"
    agenda-group "Block system"
    no-loop
	salience 10
    when
        $b: BlockingFact()
        $ip: String()
        SuspiciousIpEvent(ip == $ip)
    then
        System.out.println("Usao system alarm set");
        //$i = 1;
        //throw new Exception("Blocked");
        //System.out.println($i);
        //update($i);
        modify($b){setBlocked(true)}
        //drools.halt();
        //delete($b);
end

rule "Remove System Fact"
    agenda-group "Block system"
    no-loop
	salience 3
    when
        $b: BlockingFact()
    then
        delete($b);
end

rule "Halt system"
    agenda-group "Halt system"
    no-loop
	salience 10
    when
        $ip: String()
    then
        delete($ip);
        System.out.println("Obrisao System");
        drools.halt();
end